name: tenjin_sdk
description: A Flutter plugin to Tenjin SDK.
version: 1.0.1
homepage: https://github.com/thize/flutter_tenjin_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.5.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tenjin_sdk
        pluginClass: TenjinSdkPlugin
      ios:
        pluginClass: TenjinSdkPlugin